"""Location-related enumerations."""
from enum import Enum


class LocationType(Enum):
    """Types of locations in hierarchical order."""
    UNKWNOWN = "Unknown"
    UNIVERSE = "Universe"
    GALAXY = "Galaxy"
    STAR_SYSTEM = "Star System"
    PLANET = "Planet"
    CONTINENT = "Continent"
    REGION = "Region"
    COUNTRY = "Country"
    STATE = "State/Province"
    CITY = "City"
    DISTRICT = "District"
    BUILDING = "Building"
    ROOM = "Room"
    TEMPLE = "Temple"
    DUNGEON = "Dungeon"
    CAVE = "Cave"
    FOREST = "Forest"
    MOUNTAIN = "Mountain"
    RIVER = "River"
    LAKE = "Lake"
    OCEAN = "Ocean"
    DESERT = "Desert"
    DIMENSION = "Dimension"
    REALM = "Realm"
    PLANE = "Plane"
    OTHER = "Other"
