"""Lore-related enumerations."""
from enum import Enum


class LoreType(str, Enum):
    """Types of lore entries."""
    UNKWNOWN = "Unknown"
    MYTH = "myth"
    LEGEND = "legend"
    FOLKTALE = "folktale"
    PROPHECY = "prophecy"
    RELIGION = "religion"
    BELIEF_SYSTEM = "belief_system"
    CREATION_MYTH = "creation_myth"
    DEITY = "deity"
    SPIRIT = "spirit"
    COSMOLOGY = "cosmology"
    AFTERLIFE = "afterlife"
    MAGIC_SYSTEM = "magic_system"
    RITUAL = "ritual"
    TRADITION = "tradition"
    HOLIDAY = "holiday"
    SUPERSTITION = "superstition"
    HISTORICAL_ACCOUNT = "historical_account"
    SONG = "song"
    POEM = "poem"
    PROVERB = "proverb"
    LEGAL_CODE = "legal_code"
    PHILOSOPHY = "philosophy"
    SCIENCE = "science"
    TECHNOLOGY = "technology"
    MEDICINE = "medicine"
    ALCHEMY = "alchemy"
    ARTISTIC_TRADITION = "artistic_tradition"
    ARCHITECTURE = "architecture"
    MUSIC = "music"
    DANCE = "dance"
    LITERATURE = "literature"
    THEATER = "theater"
    FASHION = "fashion"
    CULINARY_TRADITION = "culinary_tradition"
    OTHER = "other"
